version: '3.8'

services:
  rasa_pro:
    image: rasa/rasa-pro:3.12.17
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./endpoints.yml:/app/endpoints.yml
    env_file:
      - ./.env
    environment:
      - RASA_PRO_LICENSE=${RASA_PRO_LICENSE}
    depends_on:
      - action_server

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "-m", "rasa_sdk", "--actions", "actions"]
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    env_file:
      - ./.env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rasa_pro
      - action_server
